// supabase.js
const { createClient } = supabase;

REACT_APP_SUPABASE_URL=http;//qkdevvlemcuwynbkspsk.supabase.co
REACT_APP_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrZGV2dmxlbWN1d3luYmtzcHNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MTg1MTksImV4cCI6MjA2OTA5NDUxOX0.znePO0GumUsZkkKbaLcwuVO9lHq90YtMl0ZuL0hanVw
const supabaseClient = createClient(supabaseUrl, supabaseKey);
